
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-deploy
      app: demo-voting-app
  template:
    metadata:
      name: postgres-deploy
      labels:
        app: postgres-deploy
    spec:
      containers:
        - name: postgres-deploy
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: postgres-deploy
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
