apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    name: result-deploy
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-deploy
      app: demo-voting-app
  template:
    metadata:
      name: result-deploy
      labels:
        name: result-deploy
        app: demo-voting-app
    spec:
      containers:
        - name: result-deploy
          image: kodekloud/examplevotingapp_result:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---


apiVersion: v1
kind: Service
metadata:
  name: result-service
spec:
  selector:
    name: result-deploy
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort
