apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deploy
  labels:
    name: vote-deploy
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: vote-deploy
      app: demo-voting-app
  template:
    metadata:
      name: vote-deploy
      labels:
        name: vote-deploy
        app: demo-voting-app
    spec:
      containers:
        - name: vote-deploy
          image: kodekloud/examplevotingapp_vote:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    name: vote-deploy
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort