apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: demo-voting-app
spec:
  containers:
    - name: postgres
      image: postgres
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: db-pod
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
