apiVersion: v1
kind: Pod
metadata:
  name: vote-pod
  labels:
    name: vote-pod
    app: demo-voting-app
spec:
  containers:
    - name: vote
      image: kodekloud/examplevotingapp_vote:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
  restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  selector:
    name: vote-pod
    app: demo-voting-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort
